import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:provider/provider.dart';

import '../../core/enums.dart';
import '../../core/permissions.dart';
import '../../core/routing/app_routes.dart';
import '../../core/theme/app_colors.dart';
import '../../core/theme/app_theme.dart';
import '../../core/utils/date_utils.dart';
import '../../core/utils/money.dart';
import '../../models/dealer.dart';
import '../../models/expense.dart';
import '../../state/app_state.dart';
import '../../state/data_controller.dart';
import '../../widgets/common/app_card.dart';
import '../../widgets/common/comment_thread.dart';
import '../../widgets/common/currency_display.dart';
import '../../widgets/common/data_table_card.dart';
import '../../widgets/common/detail_widgets.dart';
import '../../widgets/common/page_header.dart';
import '../../widgets/common/state_views.dart';
import '../../widgets/common/status_badge.dart';
import 'dealers_screen.dart';

/// A single dealer/vendor view: cost & contact details, the owning business,
/// the mirrored operating expense it generates, and a comment thread. Linked
/// entities resolve through the access-scoped [DataController].
class DealerDetailScreen extends StatelessWidget {
  const DealerDetailScreen({super.key, required this.dealerId});

  final String dealerId;

  @override
  Widget build(BuildContext context) {
    final data = context.watch<DataController>();
    final appState = context.watch<AppState>();
    final user = appState.currentUser;

    if (data.loading && !data.loaded) {
      return const Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          PageHeader(title: 'Dealer'),
          SizedBox(height: 48),
          LoadingView(),
        ],
      );
    }

    final dealer = data.dealerById(dealerId);
    if (dealer == null) {
      return Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          PageHeader(
            title: 'Dealer',
            actions: [
              OutlinedButton.icon(
                onPressed: () => context.go(Routes.dealers),
                icon: const Icon(Icons.arrow_back, size: 18),
                label: const Text('Back to Dealers'),
              ),
            ],
          ),
          const SizedBox(height: 48),
          const EmptyView(
            icon: Icons.search_off,
            title: 'Dealer not found',
            message: 'This dealer may have been removed or is not accessible.',
          ),
        ],
      );
    }

    final business = data.businessById(dealer.businessId);
    final currency = business?.currency ?? CurrencyCode.inr;
    // The mirrored expense (EXP-DLR-<dealerId>) generated by this dealer, if
    // it's visible in the current scope.
    final mirroredExpense = data.expenseById('EXP-DLR-${dealer.id}');
    final canEdit = user?.can(Permission.editDealer) ?? false;

    final left = Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        _SummaryCard(
          dealer: dealer,
          currency: currency,
          businessName: business?.name,
        ),
        if (mirroredExpense != null) ...[
          const SizedBox(height: AppSpacing.lg),
          _MirroredExpenseCard(expense: mirroredExpense, currency: currency),
        ],
      ],
    );

    final repo = appState.repository;
    final right = DetailActivityColumn(
      activityAt: dealer.lastActivityAt,
      comments: dealer.comments,
      canComment: canEdit,
      onPost: (comment) async {
        await repo.saveDealer(
          dealer.copyWith(comments: [...dealer.comments, comment]),
          isNew: false,
        );
        await data.refresh();
      },
    );

    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        PageHeader(
          title: dealer.name,
          subtitle: dealer.id,
          actions: [
            OutlinedButton.icon(
              onPressed: () => context.go(Routes.dealers),
              icon: const Icon(Icons.arrow_back, size: 18),
              label: const Text('Back'),
            ),
            if (canEdit)
              ElevatedButton.icon(
                onPressed: () => DealersScreen.openForm(
                    context, dealer, dealer.businessId),
                icon: const Icon(Icons.edit_outlined, size: 18),
                label: const Text('Edit'),
              ),
          ],
        ),
        const SizedBox(height: AppSpacing.lg),
        DetailTwoColumn(left: left, right: right),
      ],
    );
  }
}

class _SummaryCard extends StatelessWidget {
  const _SummaryCard({
    required this.dealer,
    required this.currency,
    required this.businessName,
  });

  final Dealer dealer;
  final CurrencyCode currency;
  final String? businessName;

  @override
  Widget build(BuildContext context) {
    final fields = <DetailField>[
      DetailField('Dealer ID', dealer.id, Icons.badge_outlined),
      DetailField('Business', businessName ?? '—', Icons.business_outlined),
      DetailField('Cost', MoneyFormatter.format(dealer.cost, currency),
          Icons.payments_outlined),
      DetailField('Frequency', dealer.costFrequency.label, Icons.repeat),
      DetailField('Contact Name', dealer.contactName, Icons.person_outline),
      DetailField('Contact Info', dealer.contactInfo, Icons.contact_page_outlined),
      DetailField(
          'Start Date',
          dealer.startDate == null ? '—' : AppDate.format(dealer.startDate),
          Icons.event_outlined),
      DetailField(
          'End Date',
          dealer.endDate == null ? '—' : AppDate.format(dealer.endDate),
          Icons.event_available_outlined),
      DetailField('Dealer URL', dealer.url, Icons.link, isLink: true),
    ];

    return SectionCard(
      title: 'Dealer Summary',
      trailing: StatusBadge.entity(dealer.status),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          DetailGrid(fields: fields),
          if (dealer.description.trim().isNotEmpty) ...[
            const SizedBox(height: AppSpacing.lg),
            const Text('Description',
                style:
                    TextStyle(fontSize: 12, color: AppColors.textSecondary)),
            const SizedBox(height: 2),
            Text(dealer.description,
                style: const TextStyle(fontSize: 14, height: 1.4)),
          ],
          if (dealer.notes.trim().isNotEmpty) ...[
            const SizedBox(height: AppSpacing.md),
            const Text('Notes',
                style:
                    TextStyle(fontSize: 12, color: AppColors.textSecondary)),
            const SizedBox(height: 2),
            Text(dealer.notes,
                style: const TextStyle(fontSize: 14, height: 1.4)),
          ],
        ],
      ),
    );
  }
}

class _MirroredExpenseCard extends StatelessWidget {
  const _MirroredExpenseCard({required this.expense, required this.currency});

  final Expense expense;
  final CurrencyCode currency;

  @override
  Widget build(BuildContext context) {
    return SectionCard(
      title: 'Linked Expense',
      subtitle: 'This dealer\'s cost is mirrored into Business Expenses',
      padding: EdgeInsets.zero,
      child: AppDataTable<Expense>(
        rows: [expense],
        rowsPerPage: 5,
        onRowTap: (e) => context.go(Routes.expenseDetailPath(e.id)),
        columns: [
          AppColumn(
            label: 'Expense',
            cell: (e) => Text(e.name,
                style: const TextStyle(fontWeight: FontWeight.w600)),
            sortValue: (e) => e.name.toLowerCase(),
          ),
          AppColumn(
            label: 'Category',
            cell: (e) =>
                StatusBadge(label: e.category.label, tone: BadgeTone.neutral),
            sortValue: (e) => e.category.label,
          ),
          AppColumn(
            label: 'Amount',
            numeric: true,
            cell: (e) => CurrencyText(e.amount, currency: currency),
            sortValue: (e) => e.amount.minor,
          ),
          AppColumn(
            label: 'Frequency',
            cell: (e) => Text(e.frequency.label),
            sortValue: (e) => e.frequency.label,
          ),
        ],
      ),
    );
  }
}
